# Generated by Django 5.1.3 on 2024-12-15 10:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Gullar turinikiriting')),
            ],
            options={
                'verbose_name': 'GulTuri',
                'verbose_name_plural': 'GulTurlari',
            },
        ),
        migrations.CreateModel(
            name='Gul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=175, verbose_name='Gul nomi')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Gul Haqida malumot')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gul/photos/', verbose_name='Gul Rasmi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('published', models.BooleanField(default=True, help_text="Agar galochka qo'ysangiz sayta chiqaradi!!!", verbose_name='Saytga chiqarish')),
                ('video', models.FileField(blank=True, null=True, upload_to='post/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi'], message='Faqat mp4 va avi formatidagilarni kiritolasiz!')])),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.turlar')),
            ],
            options={
                'verbose_name': 'Gul',
                'verbose_name_plural': 'Gullar',
                'ordering': ['-created', '-pk'],
            },
        ),
    ]
